import type { Course } from "./course-card"

export const MAIS_VENDIDOS: Course[] = [
  {
    slug: "manicure-pedicure-profissional",
    categoria: "Beleza e Estética",
    titulo: "Manicure e Pedicure: do básico ao avançado",
    instrutor: "Ana Paula Silva",
    rating: "4.9",
    alunos: "12.340",
    horas: "80h",
    preco: "R$ 47,00",
    precoDe: "R$ 297,00",
    parcelas: "ou 12x de R$ 4,70",
    selo: "mais-vendido",
    accent: "gold",
  },
  {
    slug: "eletricista-predial-completo",
    categoria: "Eletricista e Hidráulica",
    titulo: "Eletricista Predial e Industrial Completo",
    instrutor: "Carlos R. Mendes",
    rating: "4.8",
    alunos: "8.215",
    horas: "120h",
    preco: "R$ 97,00",
    precoDe: "R$ 397,00",
    parcelas: "ou 12x de R$ 9,70",
    selo: "mais-vendido",
    accent: "cyan",
  },
  {
    slug: "confeitaria-do-zero",
    categoria: "Gastronomia",
    titulo: "Confeitaria Lucrativa: do zero ao profissional",
    instrutor: "Josilene Barbosa",
    rating: "4.9",
    alunos: "15.907",
    horas: "100h",
    preco: "R$ 89,00",
    precoDe: "R$ 347,00",
    parcelas: "ou 12x de R$ 8,90",
    selo: "mais-vendido",
    accent: "lime",
  },
  {
    slug: "barbearia-moderna",
    categoria: "Beleza e Estética",
    titulo: "Barbearia Moderna: cortes, barba e acabamento",
    instrutor: "Jailson Ferreira",
    rating: "4.7",
    alunos: "6.018",
    horas: "90h",
    preco: "R$ 67,00",
    precoDe: "R$ 247,00",
    parcelas: "ou 12x de R$ 6,70",
    selo: "pix-10",
    accent: "terracotta",
  },
  {
    slug: "cuidador-de-idosos",
    categoria: "Saúde e Bem-estar",
    titulo: "Cuidador de Idosos e Enfermagem Básica",
    instrutor: "Marciel Damasceno",
    rating: "4.8",
    alunos: "9.812",
    horas: "110h",
    preco: "R$ 77,00",
    precoDe: "R$ 287,00",
    parcelas: "ou 12x de R$ 7,70",
    selo: "novo",
    accent: "green",
  },
]

export const SAUDE: Course[] = [
  {
    slug: "cuidador-idosos-avancado",
    categoria: "Saúde e Bem-estar",
    titulo: "Cuidador de Idosos e Acamados",
    instrutor: "Marciel Damasceno",
    rating: "4.8",
    alunos: "9.812",
    horas: "110h",
    preco: "R$ 77,00",
    precoDe: "R$ 287,00",
    parcelas: "ou 12x de R$ 7,70",
    selo: "mais-vendido",
    accent: "green",
  },
  {
    slug: "auxiliar-enfermagem",
    categoria: "Saúde e Bem-estar",
    titulo: "Auxiliar de Enfermagem para Clínicas",
    instrutor: "Denise Carvalho",
    rating: "4.7",
    alunos: "5.104",
    horas: "160h",
    preco: "R$ 127,00",
    precoDe: "R$ 497,00",
    parcelas: "ou 12x de R$ 12,70",
    selo: null,
    accent: "cyan",
  },
  {
    slug: "massoterapia",
    categoria: "Saúde e Bem-estar",
    titulo: "Massoterapia: técnicas corporais",
    instrutor: "Edilene Rodrigues",
    rating: "4.9",
    alunos: "4.322",
    horas: "90h",
    preco: "R$ 97,00",
    precoDe: "R$ 297,00",
    parcelas: "ou 12x de R$ 9,70",
    selo: "novo",
    accent: "terracotta",
  },
  {
    slug: "auxiliar-saude-bucal",
    categoria: "Saúde e Bem-estar",
    titulo: "Auxiliar de Saúde Bucal",
    instrutor: "Dra. Rose Aquino",
    rating: "4.8",
    alunos: "2.988",
    horas: "70h",
    preco: "R$ 87,00",
    precoDe: "R$ 267,00",
    parcelas: "ou 12x de R$ 8,70",
    selo: null,
    accent: "lime",
  },
  {
    slug: "podologia",
    categoria: "Saúde e Bem-estar",
    titulo: "Podologia Clínica e Estética",
    instrutor: "Ivaneide Souza",
    rating: "4.7",
    alunos: "3.615",
    horas: "80h",
    preco: "R$ 97,00",
    precoDe: "R$ 297,00",
    parcelas: "ou 12x de R$ 9,70",
    selo: null,
    accent: "gold",
  },
]

export const CONSTRUCAO: Course[] = [
  {
    slug: "eletricista-residencial",
    categoria: "Eletricista e Hidráulica",
    titulo: "Eletricista Residencial Completo",
    instrutor: "Carlos R. Mendes",
    rating: "4.8",
    alunos: "8.215",
    horas: "120h",
    preco: "R$ 97,00",
    precoDe: "R$ 397,00",
    parcelas: "ou 12x de R$ 9,70",
    selo: "mais-vendido",
    accent: "cyan",
  },
  {
    slug: "encanador-hidraulica",
    categoria: "Eletricista e Hidráulica",
    titulo: "Encanador: hidráulica na prática",
    instrutor: "Rogério Lima",
    rating: "4.7",
    alunos: "3.780",
    horas: "80h",
    preco: "R$ 67,00",
    precoDe: "R$ 247,00",
    parcelas: "ou 12x de R$ 6,70",
    selo: "pix-10",
    accent: "green",
  },
  {
    slug: "pedreiro-azulejista",
    categoria: "Construção Civil",
    titulo: "Pedreiro e Azulejista Profissional",
    instrutor: "Valdemir Batista",
    rating: "4.8",
    alunos: "2.410",
    horas: "100h",
    preco: "R$ 87,00",
    precoDe: "R$ 287,00",
    parcelas: "ou 12x de R$ 8,70",
    selo: null,
    accent: "terracotta",
  },
  {
    slug: "pintura-predial",
    categoria: "Construção Civil",
    titulo: "Pintura Predial e Residencial",
    instrutor: "Antônio Farias",
    rating: "4.6",
    alunos: "1.920",
    horas: "60h",
    preco: "R$ 57,00",
    precoDe: "R$ 197,00",
    parcelas: "ou 12x de R$ 5,70",
    selo: null,
    accent: "gold",
  },
  {
    slug: "ar-condicionado",
    categoria: "Construção Civil",
    titulo: "Instalação e Manutenção de Ar Condicionado",
    instrutor: "Felipe Moreira",
    rating: "4.9",
    alunos: "4.102",
    horas: "90h",
    preco: "R$ 117,00",
    precoDe: "R$ 397,00",
    parcelas: "ou 12x de R$ 11,70",
    selo: "novo",
    accent: "lime",
  },
]

export const BELEZA: Course[] = [
  {
    slug: "design-sobrancelhas",
    categoria: "Beleza e Estética",
    titulo: "Design de Sobrancelhas e Henna",
    instrutor: "Patrícia Gomes",
    rating: "4.9",
    alunos: "11.203",
    horas: "50h",
    preco: "R$ 47,00",
    precoDe: "R$ 197,00",
    parcelas: "ou 12x de R$ 4,70",
    selo: "mais-vendido",
    accent: "gold",
  },
  {
    slug: "extensao-cilios",
    categoria: "Beleza e Estética",
    titulo: "Extensão de Cílios Fio a Fio",
    instrutor: "Suellen Moraes",
    rating: "4.8",
    alunos: "7.611",
    horas: "60h",
    preco: "R$ 77,00",
    precoDe: "R$ 277,00",
    parcelas: "ou 12x de R$ 7,70",
    selo: null,
    accent: "terracotta",
  },
  {
    slug: "depilacao-profissional",
    categoria: "Beleza e Estética",
    titulo: "Depilação Profissional com Cera",
    instrutor: "Adriana Santos",
    rating: "4.7",
    alunos: "5.029",
    horas: "40h",
    preco: "R$ 57,00",
    precoDe: "R$ 197,00",
    parcelas: "ou 12x de R$ 5,70",
    selo: null,
    accent: "lime",
  },
  {
    slug: "maquiagem-profissional",
    categoria: "Beleza e Estética",
    titulo: "Maquiagem Profissional para Noivas e Eventos",
    instrutor: "Camila Rezende",
    rating: "4.9",
    alunos: "8.734",
    horas: "80h",
    preco: "R$ 97,00",
    precoDe: "R$ 347,00",
    parcelas: "ou 12x de R$ 9,70",
    selo: "novo",
    accent: "cyan",
  },
  {
    slug: "cabeleireiro-unissex",
    categoria: "Beleza e Estética",
    titulo: "Cabeleireiro Unissex: cortes e coloração",
    instrutor: "Fernanda Aguiar",
    rating: "4.8",
    alunos: "6.318",
    horas: "100h",
    preco: "R$ 127,00",
    precoDe: "R$ 447,00",
    parcelas: "ou 12x de R$ 12,70",
    selo: null,
    accent: "green",
  },
]
